name: CI — NexaCloud API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name : Checkout Python
        uses: actions/setup-python@v5
        
        with: 
          python-version : '3.11'

      - name : Installer les dépendances
        run : pip install -r ressources/requirements.txt

      - name: Installer flake8
        run: pip install flake8

      - name: lint flake8
        run : flake8 ressources/ --config ressources/.flake8

      # Ajouter la couverture de tests
      - name: Tests avec couverture
        run: pytest ressources/ -v --cov=ressources --cov-report=term-missing

      # Uploader le rapport de couverture comme artefact téléchargeable
      - name: Générer le rapport HTML
        run: pytest ressources/ --cov=ressources --cov-report=html

      - name: Upload du rapport
        uses: actions/upload-artifact@v4
        with:
          name: rapport-couverture
          path: htmlcov/
        
      # Mettre en cache les dépendances pip (accélère les builds suivants)
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('ressources/requirements.txt') }}
